version: '2'

services:

  redis:
    image: redis:3.0.3
    ports:
      - 6379:6379

  server:
    build: .
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      - '__BROKER_HOST=redis'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - redis
    command: node
